### PR TITLE
feat: Add React Native Support to ScreenShield SDK

### PR DESCRIPTION
**Pull request by gulsher7**
I've added React Native compatibility to the ScreenShield SDK, extending its usability to React Native developers. I have also added the ReactNativeExample directory in this root project. Open to feedback and collaboration for further improvements.

### CODE REVIEW

**Comment by JayantBadlani** [comment]
Hi @gulsher7 ,

Thank you for your valuable contribution to the ScreenShield SDK! I appreciate your effort in adding React Native compatibility. While I'm primarily an iOS developer and not well-versed in React Native, I'm open to collaboration and improvement.

Before merging the pull request, I'd like to ensure that the React Native compatibility has been thoroughly tested. Could you provide some assurance regarding its functionality in React Native projects and confirm that it won't impact the existing native iOS code? This would help me feel more confident in merging your changes.

Looking forward to your response and further collaboration.

Best,
Jayant

**Comment by gulsher7** [comment]
Hey @JayantBadlani,

We are using this sdk in one of our client project, basically it’s
educational app where we prevent users to record the lectures video.

Regarding your concern, I can assure you that the React Native
compatibility I added to the ScreenShield SDK has been thoroughly tested.
It functions seamlessly within React Native projects and doesn't impact the
existing native iOS code at all. The changes made in the pull request only
involve creating a bridge in the React Native side to integrate the
ScreenShield SDK. Both React Native and native iOS functionalities work
independently, ensuring no adverse effects on the native side. Looking
forward to further collaboration and merging the changes.

I also love to contribute to open-source projects. I've created just one or
two open-source projects for our community. You can check them out as well
to ensure that I'm a genuine contributor.

1. React Native Boilerplate:
https://www.npmjs.com/package/brew-react-native-kit

2. React Native Bg Location :
https://www.npmjs.com/package/react-native-bg-location

My Linkdin profile :
https://www.linkedin.com/in/gulsherk?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app


Best regards
Gulsher

**Comment by JayantBadlani** [comment]
Hi @gulsher7,

Thank you for the detailed information and assurance regarding React Native compatibility for the ScreenShield SDK. It's great to hear that it has been thoroughly tested and won't impact the existing native iOS code.

Regarding the integration into the ScreenShield SDK, is there anything specific you'd like me to do on the React Native side, such as package? Do you want to suggest any changes in the code, or is everything good to go for merging the changes?

Looking forward to your guidance on this.

Best regards,
Jayant

**Comment by gulsher7** [comment]
Yes, it's fine, you are good to go.

**Pull request merged**
